### ISSUE TITLE
installation issue m1

### ISSUE THREAD

**Issue by thegallier** [ItsPi3141/alpaca-electron#5]
i am getting the below when i open the application.  (the the app opens but i can not select the path).  osx m1.

/====

at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
at Module._load (internal/modules/cjs/loader.js:732:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Volumes/Extreme Pro/llama/alpaca-electron/release-builds/AlpacaElectron-darwin-arm64/AlpacaElectron.app/Contents/Resources/app/node_modules/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:6:11)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
at Module.load (internal/modules/cjs/loader.js:935:32)

**Comment by ItsPi3141** [comment]
So this error pops up when you open the file picker?

**Comment by thegallier** [comment]
no when you open the app

**Comment by ItsPi3141** [comment]
Does the app window show up? Or does it just show this error right away before displaying anything
